commit_message: "Initial commit"
seed: 42

model:
  name_or_path: "google/gemma-3-270m-it"
  use_bf16: true

wandb:
  enabled: true
  project: "uncertainty-aware-alignment"
  name: "gemma-3-270m-it_ditto"
  group: ["ditto"]
  tags: ["gemma-3", "270m"]
  notes: "DITTO training on gemma-3-270m-it"

dataset:
  name_or_path: "belati/ccat50"
  batch_size: 12
  max_length: 512
  num_workers: 1

  num_authors: 4
  train_samples_per_author: 4
  eval_samples_per_author: 4

optimizer:
  lr: 5.0e-6
  weight_decay: 0.01

trainer:
  sample_during_eval: true
  epochs: 1
  beta: 0.1
  warmup_steps: 100
  max_grad_norm: 1.0
  logging_steps: 10
  save_steps: 500
  eval_steps: 250
  push_to_hub: true
  repo_id: "belati/gemma-3-270m-it_ditto"
  gradient_accumulation_steps: 8
  max_length: 512

resample:
  frac_expert: 0.7
  frac_replay: 0.2
  frac_noisy: 0.1
  rescale_batch: 3
  bootstrap_count: 10
