commit_message: "Initial commit"
seed: 42

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules:
    - all-linear

model:
  device: "cuda"
  attn_implementation: "flash_attention_2" # "flash_attention_2" if cuda
  name_or_path: "mistralai/Ministral-8B-Instruct-2410"
  use_bf16: true

wandb:
  enabled: true
  project: "ditto"
  name: "ministral8binstruct_ditto"
  group: "ditto"
  tags: ["ministral", "8b"]
  notes: "DITTO training on Ministral-8B-Instruct-2410"

dataset:
  name_or_path: "belati/review-sentiment"
  batch_size: 4
  max_length: 512
  num_workers: 0

  num_eval_samples: 2

optimizer:
  lr: 5.0e-5 # x10 learning rate for LoRA, default was 5e-6
  weight_decay: 0.01

trainer:
  sample_during_eval: true
  epochs: 100
  beta: 0.1
  warmup_steps: 100
  max_grad_norm: 1.0
  logging_steps: 10
  save_steps: 500
  eval_steps: 20
  push_to_hub: false
  repo_id: "belati/Ministral-8B-Instruct-2410_ditto"
  gradient_accumulation_steps: 1
  max_length: 512
  use_vllm: true
  vllm:
    gpu_mem_util: 0.4
    enable_sleep_mode: true
    batch_size: 2
    rescale_batch: 2
    bootstrap_count: 2

resample_rate: 25
resample:
  frac_expert: 0.7
  frac_replay: 0.2
  frac_noisy: 0.1
  rescale_batch: 2
  bootstrap_count: 4
