commit_message: "Initial commit"
seed: 42

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj

model:
  device: "mps"
  name_or_path: "HuggingFaceTB/SmolLM2-135M-Instruct"
  use_bf16: true

wandb:
  enabled: false
  project: "uncertainty-aware-alignment"
  name: "SmolLM2-135M-Instruct_ditto"
  group: "ditto"
  tags: ["SmolLM2", "135m"]
  notes: "DITTO training on SmolLM2-135M-Instruct"

dataset:
  name_or_path: "belati/ccat50"
  batch_size: 2
  max_length: 512
  num_workers: 0

  num_authors: 1
  train_samples_per_author: 4
  eval_samples_per_author: 4

optimizer:
  lr: 5.0e-6
  weight_decay: 0.01

trainer:
  sample_during_eval: true
  epochs: 10
  beta: 0.1
  warmup_steps: 100
  max_grad_norm: 1.0
  logging_steps: 10
  save_steps: 500
  eval_steps: 20
  push_to_hub: false
  repo_id: "belati/SmolLM2-135M-Instruct_ditto"
  gradient_accumulation_steps: 1
  max_length: 512

resample_rate: 20
resample:
  frac_expert: 0.7
  frac_replay: 0.2
  frac_noisy: 0.1
  rescale_batch: 2
  bootstrap_count: 2
