run_dir: "experiments/pythia-160m-dpo"
commit_message: "Test"
seed: 42
push_to_hub: False

model:
  name_or_path: "experiments/pythia-160m-sft/model" 
  beta: 0.1

dataset:
  name_or_path: "HuggingFaceH4/ultrafeedback_binarized"
  split: "train_prefs"
  batch_size: 4
  max_length: 1024
  num_workers: 1
  # float for fraction; int for count.
  subset_size: 0.1

optimizer:
  lr: 5.0e-6
  weight_decay: 0.01

trainer:
  epochs: 1
  warmup_steps: 100
  max_grad_norm: 1.0
  logging_steps: 10
  save_steps: 500
  eval_steps: 250
  repo_id: "belati/pythia160m_dpo"
